/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class test_HelloJava */

#ifndef _Included_test_HelloJava
#define _Included_test_HelloJava
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     test_HelloJava
 * Method:    helloBlub
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_test_HelloJava_helloBlub
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
