/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class start_JNIHello */

#ifndef _Included_start_JNIHello
#define _Included_start_JNIHello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     start_JNIHello
 * Method:    helloJNI
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_start_JNIHello_helloJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
